config/routes.rb
Rails.application.routes.draw do
  resources :components
  resources :dishes
  resources :categories

  root to: 'dishes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :dish

  validates :amount, presence: true
  validates :measure_unit, presence: true
  validates :ingredient, presence: true
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  # has_many :attachments, ->{ordering}, dependent: :destroy, inverse_of: :dish
  # accepts_nested_attributes_for :attachments, allow_destroy: true

  has_attached_file :image, styles: {medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\image/, size: {in: 0..10.megabytes}

  has_many :components, dependent: :destroy
  accepts_nested_attributes_for :components, allow_destroy: true

  scope :ordering, ->{order(:name)}

  validates :name, presence: true
  validates :time_for_cook, presence: true
  validates :instructions, presence: true

  attr_reader :files

  def files=(val)
    val.each_with_index do |file, i|
      self.attachments.build(image: file, position: attachments.maximum(:position).to_i + i + 1)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  before_action :set_component, only: [:show, :edit, :update, :destroy]

  # GET /components
  # GET /components.json
  def index
    @components = Component.all
  end

  # GET /components/1
  # GET /components/1.json
  def show
  end

  # GET /components/new
  def new
    @component = Component.new
  end

  # GET /components/1/edit
  def edit
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(component_params)

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render :show, status: :created, location: @component }
      else
        format.html { render :new }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /components/1
  # PATCH/PUT /components/1.json
  def update
    respond_to do |format|
      if @component.update(component_params)
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { render :show, status: :ok, location: @component }
      else
        format.html { render :edit }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component.destroy
    respond_to do |format|
      format.html { redirect_to components_url, notice: 'Component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component
      @component = Component.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_params
      params.require(:component).permit(:dish_id, :amount, :units, :ingredient_id)
    end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    if Dish.count != 0
      if params.key?(:id)
        redirect_to dish_url(id: params[:id], search: params[:search])
      else
        redirect_to dish_url(id: 1, search: params[:search])
      end
    end
    # raise params.inspect
    # if params.key?(:search)
    #   @dishes = Dish.where("name LIKE ?", "%#{params[:search]}%")
    # else
    #   @dishes = Dish.all
    # end
    # @images = Hash.new
    # @components = Hash.new
    # @dishes.each do |dish|
    #   @images["#{dish.id}"] = Attachment.where(dish_id: dish.id).first.image
    #   @components["#{dish.idindex.html.haml}"] = Component.where(dish_id: dish.id)
    # end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    # raise params.inspect
    if params.key?(:search)
      # raise params.inspect
      @dishes = Dish.where("name ILIKE ?", "%#{params[:search]}%").order(:id)
    else
      @dishes = Dish.all.order(:id)
    end
    # @images = Hash.new
    @components = Hash.new
    # @images["#{@dish.id}"] = Attachment.where(dish_id: @dish.id).first.image
    @components["#{@dish.id}"] = Component.where(dish_id: @dish.id)
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
    @dish.components.build
    # @dish.attachments.build
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: t('views.created') }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: t('views.updated') }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: t('views.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :time_for_cook, :instructions, :appliances_used, :image, components_attributes: [:id, :dish, :amount, :measure_unit, :ingredient, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/application/_alerts.html.haml
- flash.each do |key, value|
  - if key == 'warning'
    .alert.alert-warning.alert-dismissible.bg-warning{role: "alert"}
      %button{ type: "button", class: "close", "data-dismiss" => "alert", "aria-label" => "Close"}
        %span{ "aria-hidden" => "true"} &times;
      = value
  - else
    .alert.alert-notice.alert-dismissible.bg-success{role: "alert"}
      %button{ type: "button", class: "close", "data-dismiss" => "alert", "aria-label" => "Close"}
        %span{ "aria-hidden" => "true"} &times;
      = value

app/views/application/_footer.html.haml
%footer.footer.navbar-fixed-bottom
  .container-fluid
    .panel-footer sidorova.lubovvs@gmail.com

app/views/application/_navbar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a{:href => root_path}
        .image_brand
          = image_tag 'food.png', size: '40x40'
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if params[:action] == "create"
          %li
            %a{:href => root_path}
              Все блюда
              %span.sr-only (current)
          %li.active
            %a{:href => new_dish_path}= t('views.New Dish')
        - else
          %li.active
            %a{:href => root_path}
              Все блюда
              %span.sr-only (current)
          %li
            %a{:href => new_dish_path}= t('views.New Dish')
        -# %li.dropdown
        -#   %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
        -#     Dropdown
        -#     %span.caret
        -#   %ul.dropdown-menu
        -#     %li
        -#       %a{:href => "#"} Action
        -#     %li
        -#       %a{:href => "#"} Another action
        -#     %li
        -#       %a{:href => "#"} Something else here
        -#     %li.divider{:role => "separator"}
        -#     %li
        -#       %a{:href => "#"} Separated link
        -#     %li.divider{:role => "separator"}
        -#     %li
        -#       %a{:href => "#"} One more separated link
      -# %form.navbar-form.navbar-left{:role => "search"}
      -#   .form-group
      -#     %input.form-control{:placeholder => "Search", :type => "text"}
      -#   %button.btn.btn-default{:id => "mybutton", :type => "submit"} Submit
      = form_tag root_path, {role: "search", class: "navbar-form navbar-left", method: :get} do
        .form-group
          = search_field_tag "search", nil, class: "form-control", type: "text", placeholder: t('views.Search')
          = submit_tag t('views.Search'), class: "btn btn-default"
      -# %ul.nav.navbar-nav.navbar-right
      -#   %li => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      -#       Dropdown
      -#       %span.caret
      -#     %ul.dropdown-menu
      -#       %li
      -#         %a{:href => "#"} Action
      -#       %li
      -#         %a{:href => "#"} Another action
      -#       %li
      -#         %a{:href => "#"} Something else here
      -#       %li.divider{:role => "separator"}
      -#       %li
      -#         %a{:href => "#"} Separated link

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.text_field :category
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th Category
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.category
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Category:
  = @category.category

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/dishes/_form.html.haml
= bootstrap_nested_form_for(@dish) do |f|
  - if @dish.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dish.errors.count, "error")} prohibited this dish from being saved:"
      %ul
        - @dish.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :name
  = f.text_field :time_for_cook
  = f.text_field :instructions
  = f.text_field :appliances_used
  = f.file_field :image

  #component
    = f.fields_for :components do |component_form|
      .row
        .col-md-3
          = component_form.text_field :ingredient
        .col-md-3
          = component_form.number_field :amount, step: 0.25
        .col-md-3
          = component_form.text_field :measure_unit
        .col-md-3.remove
          = component_form.link_to_remove t('views.Remove this component'), role: "button", class: 'btn btn-default'
  = f.link_to_add t('views.Add a component'), :components, :data => { :target => "#component" }, role: "button", class: 'btn btn-default'
  = f.submit t('views.Save')

app/views/dishes/edit.html.haml
.container-fluid
  .page-header
    %h1= t('views.Edit')
  = render 'form'

app/views/dishes/index.html.haml
.container-fluid
  .row
    .col-md-4.col-xs-4.col-sm-4
    .col-md-4.col-xs-4.col-sm-4
      = image_tag 'cookbook.gif', class: "img-responsive"
      %p
        =link_to t('views.New Dish'), new_dish_path, role: "button", class: 'btn btn-default'
    .col-md-4.col-xs-4.col-sm-4

app/views/dishes/new.html.haml
.container-fluid
  .page-header
    %h1= t('views.New Dish')
  = render 'form'

app/views/dishes/show.html.haml
.container-fluid
  = render 'alerts'
  .page-header
    %h1= @dish.name
  .col-md-3
    .list-group
      - @dishes.each_with_index do |dish, i|
        = link_to dish.name, dish, type: "button", class: "list-group-item"
  .col-md-9
    .panel.panel-default
      .panel-heading
        %b= t('activerecord.attributes.dish.time_for_cook')
        = @dish.time_for_cook
        = t('views.min')
      .panel-body
        .row
          .col-md-4
            %p= image_tag @dish.image, class: "img-responsive"
          .col-md-8
            %table.table
              %thead
                %tr
                  %th= t('activerecord.attributes.component.ingredient')
                  %th= t('activerecord.attributes.component.amount')
                  %th= t('activerecord.attributes.component.measure_unit')
              %tbody
              - @components["#{@dish.id}"].each do |i|
                %tr
                  %td= i.ingredient
                  %td= i.amount
                  %td= i.measure_unit
        %p
          = @dish.instructions
        %p
          %b= t('activerecord.attributes.dish.appliances_used')
          = @dish.appliances_used
        %p
          =link_to t('views.Edit'), edit_dish_path(@dish), role: "button", class: 'btn btn-default'
          =link_to t('views.Destroy'), @dish, role: "button", class: 'btn btn-danger', data: {method: :delete, confirm: 'Вы уверены?'}

    %br
    -# = link_to 'Back', dishes_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cookbook
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'navbar'
    = yield
    -# = render 'footer'